name: StyleSpark
description: Analyzing and Matching Code to Iconic Programming Styles
author: Kevin Loeffler

inputs:
  file-extensions:
    description: 'File extensions to analyze (comma-separated)'
    required: true
    default: '.py,.js,.java'

runs:
  using: docker
  image: Dockerfile
  env:
    FILE_EXTENSIONS: ${{ inputs.file-extensions }}
  steps:
    - name: Check out repository
      uses: actions/checkout@v2
