name: StyleSpark
description: Analyzing and Matching Code to Iconic Programming Styles
author: Kevin Loeffler

inputs:
  file-extensions:
    description: 'File extensions to analyze (comma-separated)'
    required: true
    default: '.py,.js,.java'
  readme-path:
    description: 'Path to the README file to update'
    required: false
    default: 'README.md'
  commit-changes:
    description: 'Commit changes to the repository automatically (true/false)'
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Run Docker container
      run: |
        docker build -t stylespark .
        docker run -e FILE_EXTENSIONS="${{ inputs.file-extensions }}" -e COMMIT_CHANGES="${{ inputs.commit-changes }}" -e README_PATH="${{ inputs.readme-path }}" stylespark